services:
  - type: worker
    name: discord-trybot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
